package cn.edu.xmu.privilegegateway.privilegeservice.mapper;

import cn.edu.xmu.privilegegateway.privilegeservice.model.po.GroupRolePo;
import cn.edu.xmu.privilegegateway.privilegeservice.model.po.GroupRolePoExample;
import java.util.List;

public interface GroupRolePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    int insert(GroupRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    int insertSelective(GroupRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    List<GroupRolePo> selectByExample(GroupRolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    GroupRolePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupRolePo record);
}