package cn.edu.xmu.privilegegateway.privilegeservice.mapper;

import cn.edu.xmu.privilegegateway.privilegeservice.model.po.GroupPo;
import cn.edu.xmu.privilegegateway.privilegeservice.model.po.GroupPoExample;
import java.util.List;

public interface GroupPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    int insert(GroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    int insertSelective(GroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    List<GroupPo> selectByExample(GroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    GroupPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupPo record);
}