package cn.edu.xmu.privilegegateway.privilegeservice.mapper;

import cn.edu.xmu.privilegegateway.privilegeservice.model.po.RoleInheritedPo;
import cn.edu.xmu.privilegegateway.privilegeservice.model.po.RoleInheritedPoExample;
import java.util.List;

public interface RoleInheritedPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    int insert(RoleInheritedPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    int insertSelective(RoleInheritedPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    List<RoleInheritedPo> selectByExample(RoleInheritedPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    RoleInheritedPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleInheritedPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_inherited
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleInheritedPo record);
}