server:
  port: 8080

spring:
  application:
    name: privilege-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.4.136
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        #权限模块
        - id: privilege-nologin
          uri: privilge-service
          predicates:
            - Path=/privilege/login, /privilege/states, /privilege/self/**
          filters:
            - RewritePath=/privilege/?(?<segment>.*), /$\{segment}

        - id: privilege-login
          uri: privilge-service
          predicates:
            - Path=/privilege/**
          filters:
            - RewritePath=/privilege/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: activity-nologin
          uri: activity-service
          predicates:
            - Path=/activity/advancesales/states, /activity/advancesales, /activity/advancesales/{id}, /activity/groupons/states, /activity/shareactivities/states
            - Method=GET
          filters:
            - RewritePath=/activity/(?<segment>.*), /$\{segment}

        - id: activity-login
          uri: activity-service
          predicates:
            - Path=/activity/**
          filters:
            - RewritePath=/activity/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: freight-nologin
          uri: freight-service
          predicates:
            - Path=/freight/regions/{id}/ancestor, /freight/regions/{id}/subregions
            - Method=GET
          filters:
            - RewritePath=/freight/(?<segment>.*), /$\{segment}

        - id: freight-login
          uri: freight-service
          predicates:
            - Path=/freight/**
          filters:
            - RewritePath=/freight/(?<segment>.*), /$\{segment}            -
            - Auth=authorization

        - id: goods-nologin
          uri: goods-service
          predicates:
            - Path=/goods/products/**, /goods/goods/{id}
            - Method=GET
          filters:
            - RewritePath=/goods/(?<segment>.*), /$\{segment}

        - id: goods-login
          uri: goods-service
          predicates:
            - Path=/goods/**
          filters:
            - RewritePath=/goods/(?<segment>.*), /$\{segment}            -
            - Auth=authorization

        - id: comment-nologin
          uri: comment-service
          predicates:
            - Path=/comment/comments/states, /comment/products/{id}/comments
            - Method=GET
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}

        - id: comment-login
          uri: comment-service
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}            -
            - Auth=authorization

        - id: coupon-nologin
          uri: coupon-service
          predicates:
            - Path=/coupon/couponactivities/states, /coupon/couponactivities, /coupon/couponactivities/{id}/products, /coupon/products/{id}/couponactivities
            - Method=GET
          filters:
            - RewritePath=/coupon/(?<segment>.*), /$\{segment}

        - id: coupon-login
          uri: coupon-service
          predicates:
            - Path=/coupon/**
          filters:
            - RewritePath=/coupon/(?<segment>.*), /$\{segment}            -
            - Auth=authorization

        - id: shop-nologin
            uri: shop-service
            predicates:
              - Path=/shop/shops/states, /shop/shops/{id}, /shop/categories/{id}/subcategories
              - Method=GET
            filters:
              - RewritePath=/shop/(?<segment>.*), /$\{segment}

              - id: shop-login
                uri: shop-service
                predicates:
                  - Path=/shop/**
                filters:
                  - RewritePath=/shop/(?<segment>.*), /$\{segment}            -
                  - Auth=authorization

  redis:
    host: 192.168.31.241
    database: 0
    password: 12345678

management:
  endpoint:
    gateway:
      enabled: true

# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 172.16.3.137
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2

# 网关token相关配置
privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60
