server:
  port: 8080

spring:
  application:
    name: privilege-gateway
  cloud:
    nacos:
      discovery:
        server-addr:  121.36.41.192
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        #权限模块
        - id: privilege-nologin
          uri: lb://privilege-service
          predicates:
            - Path=/privilege/login, /privilege/*/states,/privilege/self/password/reset,/privilege/self/password
          filters:
            - RewritePath=/privilege/?(?<segment>.*), /$\{segment}

        - id: privilege-login
          uri: lb://privilege-service
          predicates:
            - Path=/privilege/departs/{did}/**, /privilege/**
          filters:
            - RewritePath=/privilege/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: activity-nologin
          uri: lb://activity-service
          predicates:
            - Path=/activity/advancesales/states, /activity/advancesales, /activity/advancesales/{id}, /activity/*/states
            - Method=GET
          filters:
            - RewritePath=/activity/(?<segment>.*), /$\{segment}

        - id: activity-login
          uri: lb://activity-service
          predicates:
            - Path=/activity/shops/{did}/**
          filters:
            - RewritePath=/activity/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: freight-nologin
          uri: lb://freight-service
          predicates:
            - Path=/freight/regions/{id}/ancestor, /freight/regions/{id}/subregions
            - Method=GET
          filters:
            - RewritePath=/freight/(?<segment>.*), /$\{segment}

        - id: freight-login
          uri: lb://freight-service
          predicates:
            - Path=/freight/shops/{did}/**
          filters:
            - RewritePath=/freight/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: goods-nologin
          uri: lb://goods-service
          predicates:
            - Path=/goods/products/**, /goods/goods/{id}
            - Method=GET
          filters:
            - RewritePath=/goods/(?<segment>.*), /$\{segment}

        - id: goods-login
          uri: lb://goods-service
          predicates:
            - Path=/goods/shops/{did}/**
          filters:
            - RewritePath=/goods/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: comment-nologin
          uri: lb://comment-service
          predicates:
            - Path=/comment/comments/states, /comment/products/{id}/comments
            - Method=GET
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}

        - id: comment-login
          uri: lb://comment-service
          predicates:
            - Path=/comment/shops/{did}/**,/comment/**
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: coupon-nologin
          uri: lb://coupon-service
          predicates:
            - Path=/coupon/couponactivities/states, /coupon/couponactivities, /coupon/couponactivities/{id}/products, /coupon/products/{id}/couponactivities
            - Method=GET
          filters:
            - RewritePath=/coupon/(?<segment>.*), /$\{segment}

        - id: coupon-login
          uri: lb://coupon-service
          predicates:
            - Path=/coupon/shops/{did}/**
          filters:
            - RewritePath=/coupon/(?<segment>.*), /$\{segment}
            - Auth=authorization

        - id: shop-nologin
          uri: lb://shop-service
          predicates:
            - Path=/shop/shops/states, /shop/shops/{id}, /shop/categories/{id}/subcategories, /shop/categories/{id}/parents
            - Method=GET
          filters:
            - RewritePath=/shop/(?<segment>.*), /$\{segment}

        - id: shop-login
          uri: lb://shop-service
          predicates:
            - Path=/shop/shops/{did}/**,/shop/shops/**
          filters:
            - RewritePath=/shop/(?<segment>.*), /$\{segment}
            - Auth=authorization

  redis:
    host: 121.36.41.192
    database: 0
    password: 123456

management:
  endpoint:
    gateway:
      enabled: true

rocketmq:
  name-server: 172.16.3.137
  producer:
    group: producer_group
    max-message-size: 4096
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2


privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60
  retry: 3
