spring:
  redis:
    host: 121.36.53.115
    database: 0
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.36.41.192:3306/privilege_gateway?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: dbuser
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.41.192
  application:
    name: privilege-service


mybatis:
  type-aliases-package: cn.edu.xmu.privilegegateway.privilegeservice.model.po
  mapper-locations: classpath*:cn.edu.xmu.privilegegateway.privilegeservice.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

privilegeservice:
  initialization: false
  lockerExpireTime: 30
  dav:
    username: ooad_javaee
    password: 12345678
    baseUrl: http://172.16.4.1/webdav/test
  user:
    expiretime: 600
  role:
    expiretime: 600
  login:
    multiply: false
    jwtExpire: 3600
  bloomfilter:
    new-user-email:
      error-rate: 0.001
      capacity: 1000
    new-user-mobile:
      error-rate: 0.001
      capacity: 1000
    new-user-name:
      error-rate: 0.001
      capacity: 1000

pagehelper:
  helper-dialect: mysql

server:
  port: 8087
  tomcat:
    threads:
      max: 200
