spring:
  redis:
    host: 101.132.164.244
    port: 6889
    database: 0
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/privilege_gateway?serverTimezone=GMT%2B8
    username: dbuser
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: 10.30.64.225:8848
mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.privilegegateway.privilegeservice.model.po
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.privilegegateway.privilegeservice.mapper/*.xml
#  mapper-locations: classpath*:mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

privilegeservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: false
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #dav信息配置
  dav:
    #dav服务器用户名
    username: other
    #dav服务器密码
    password: 123456
    #dav服务器路径
    baseUrl: http://106.52.203.83/webdav/
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600
  #Bloom过滤器参数
  bloomfilter:
    #新注册用户的Email Bloom过滤器
    new-user-email:
      #错误率
      error-rate: 0.001
      #容量
      capacity: 1000
    #新注册用户的电话 Bloom过滤器
    new-user-mobile:
      #错误率
      error-rate: 0.001
      #容量
      capacity: 1000
    #新注册用户的用户名 Bloom过滤器
    new-user-name:
      #错误率
      error-rate: 0.001
      #容量
      capacity: 1000

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
